#!/usr/bin/env python3
"""
audit_published_pages.py — published-pages regression audit for paper-three-pass-reader

Reads published_pages.json (live URL or local file), fetches every page, and checks
for regressions against the v0.2.9+ renderer/template expectations:

  A. HTTP / fetch                (error if non-200 or empty)
  B. Template tag leak           (error if any {% %} / {{ }} / {% else %} / {# #} leak)
  C. Old footer / old renderer   (error if v0.1.0-alpha / raw dict repr / etc.)
  D. zh-CN UI markers            (warning if a -cn / Chinese page is missing 5+ zh markers)
  E. Resolver trail              (warning if missing in v0.2.8+ page)
  F. Claims / Evidence           (warning if claims section missing or all claim IDs empty)
  G. Glossary                    (warning if section missing for non-screenshot-only)
  H. Essay / talk rendering      (warning if essay page missing 实践计划 / 结构说明 / 相关脉络)
  I. Root index / manifest       (warning if pages count mismatches manifest)

stdlib-only. No external deps.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import html as _html
import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Dict, List, Optional, Tuple

# ----------------------------------------------------------------------------
# Constants
# ----------------------------------------------------------------------------

ZH_CN_MARKERS = [
    "输入解析状态",
    "摘要",
    "论文地图",
    "主张",
    "证据",
    "最终理解检查表",
]

ESSAY_SLUG_HINTS = (
    "you-and-your-research",
    "essay",
    "talk",
    "lecture",
    "keynote",
)

ESSAY_REQUIRED_MARKERS = [
    "实践计划",   # Practical Plan
    "结构说明",   # Figures & Tables -> 结构说明 in essay mode
    "相关脉络",   # Related Work -> 相关脉络 in essay mode
]

EVIDENCE_LABELS = [
    "[Paper evidence]",
    "[Figure/Table evidence]",
    "[Author claim]",
    "[Agent inference]",
    "[Uncertain]",
    "[Needs verification]",
]

# ----------------------------------------------------------------------------
# HTTP helpers
# ----------------------------------------------------------------------------

def _http_get(url: str, timeout: float = 20.0) -> Tuple[int, str]:
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "paper-three-pass-reader-audit/0.1 (+https://conanxin.github.io/paper-reading-pages/)"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            status = getattr(resp, "status", None) or resp.getcode()
            raw = resp.read()
            try:
                body = raw.decode("utf-8", errors="replace")
            except Exception:
                body = raw.decode("latin-1", errors="replace")
            return int(status), body
    except urllib.error.HTTPError as e:
        try:
            raw = e.read()
            body = raw.decode("utf-8", errors="replace")
        except Exception:
            body = ""
        return int(e.code), body
    except (urllib.error.URLError, TimeoutError, OSError) as e:
        return 0, ""


def _extract_title(body: str) -> str:
    m = re.search(r"<title[^>]*>(.*?)</title>", body, flags=re.IGNORECASE | re.DOTALL)
    if not m:
        return ""
    return re.sub(r"\s+", " ", m.group(1)).strip()


# ----------------------------------------------------------------------------
# Issue construction
# ----------------------------------------------------------------------------

def _mk_issue(severity: str, code: str, message: str, recommendation: str = "") -> Dict[str, str]:
    return {
        "severity": severity,
        "code": code,
        "message": message,
        "recommendation": recommendation,
    }


# ----------------------------------------------------------------------------
# Check functions
# ----------------------------------------------------------------------------

def _check_template_leak(body: str) -> List[Dict[str, str]]:
    issues: List[Dict[str, str]] = []
    leaks = []
    for needle, label in [
        ("{% else %}", "{% else %}"),
        ("{%", "{%"),
        ("%}", "%}"),
        ("{{", "{{"),
        ("}}", "}}"),
        ("{#", "{#"),
        ("#}", "#}"),
        ("No key references recorded", "No key references recorded"),
    ]:
        if needle in body:
            leaks.append(label)
    if leaks:
        issues.append(_mk_issue(
            "error",
            "template_leak",
            "渲染页包含未闭合的 template tag 或占位符: " + ", ".join(sorted(set(leaks))),
            "重新用 v0.2.9+ 渲染器 (render_page.py) 渲染该页面,确认 mini-template 的 {% else %} 分支已处理。",
        ))
    return issues


def _check_old_footer(body: str) -> List[Dict[str, str]]:
    issues: List[Dict[str, str]] = []
    for needle in [
        "v0.1.0-alpha",
        "Generated by paper-three-pass-reader v0.1.0-alpha",
        "Generated by paper-three-reader v0.1.0-alpha",
    ]:
        if needle in body:
            issues.append(_mk_issue(
                "error",
                "old_footer",
                f"页面仍显示旧版本 footer: '{needle}'",
                "重新渲染该页面以使用 v0.2.9+ 的 generator_version footer。",
            ))
            break
    return issues


def _check_raw_dict(body: str) -> List[Dict[str, str]]:
    issues: List[Dict[str, str]] = []
    if re.search(r"\{'label'\s*:", body):
        issues.append(_mk_issue(
            "error",
            "raw_dict",
            "页面含 raw Python dict repr (例如 {'label': ...})。",
            "重新用 v0.2.9+ renderer (render_page.py) 渲染;Five Cs 现在被 normalize_five_cs 展平为 {label,value,evidence_label,note}。",
        ))
    return issues


def _check_resolver_trail(body: str, url: str) -> List[Dict[str, str]]:
    has_resolver_en = ("Resolver Trail" in body) or ("Resolver status" in body) or ("Confidence" in body and "Matched" in body)
    has_resolver_zh = ("解析状态" in body) or ("置信度" in body) or ("匹配 arXiv ID" in body) or ("匹配论文" in body)
    if not (has_resolver_en or has_resolver_zh):
        return [_mk_issue(
            "warning",
            "missing_resolver_trail",
            "页面缺少 Resolver Trail / 解析状态 区段,可能是 v0.2.7 之前渲染的旧页面。",
            "重新用 v0.2.8+ renderer 渲染;source_resolution_utils 会输出 Resolver status / Confidence / Matched paper 等。",
        )]
    return []


def _check_claims(body: str) -> List[Dict[str, str]]:
    issues: List[Dict[str, str]] = []
    if not (("Claims" in body) or ("主张" in body) or ("Claim" in body) or ("证据" in body) or ("Evidence" in body)):
        issues.append(_mk_issue(
            "warning",
            "missing_claims_section",
            "页面缺少 Claims / Evidence 区段。",
            "确认 paper_reading.json 含 claims_evidence_map,重新渲染。",
        ))
        return issues
    # Detect empty claim IDs
    if re.search(r"<code>\s*</code>", body):
        issues.append(_mk_issue(
            "warning",
            "empty_claim_id",
            "页面包含 <code></code> 空 claim ID 单元格。",
            "重新渲染;v0.2.9+ normalize_claim 会从 id 派生 claim_id。",
        ))
    # Detect at least one claim ID
    if not re.search(r">C\d{2,}<", body):
        issues.append(_mk_issue(
            "info",
            "no_visible_claim_id",
            "页面没有可见的 claim ID (例如 C01/C02)。",
            "如果页面是弱输入(screenshot_only/abstract_only),可忽略;否则检查 paper_reading.json 的 claim id 字段。",
        ))
    # Detect at least one evidence label
    if not any(lbl in body for lbl in EVIDENCE_LABELS):
        issues.append(_mk_issue(
            "info",
            "no_evidence_label",
            "页面未出现任何 evidence label。",
            "如果页面是弱输入,可忽略;否则为每个 claim/figure 字段加 [Paper evidence] / [Author claim] 等标签。",
        ))
    return issues


def _check_glossary(body: str) -> List[Dict[str, str]]:
    issues: List[Dict[str, str]] = []
    has_glossary = ("Glossary" in body) or ("术语" in body) or ("关键术语" in body)
    if not has_glossary:
        issues.append(_mk_issue(
            "warning",
            "missing_glossary",
            "页面缺少 Glossary / 关键术语 区段。",
            "如果页面是 screenshot_only,可忽略;否则补 paper_reading.json 的 glossary 字段并重新渲染。",
        ))
        return issues
    # v0.2.9+ exposes explicit chip-body with definition; warn if chip without def
    if re.search(r'class="chip"', body) and not re.search(r'class="chip-body"', body) and "v0.2.9" not in body:
        # weak check — old glossary chips used tooltips only
        issues.append(_mk_issue(
            "info",
            "glossary_no_explicit_definition",
            "Glossary 仍是 v0.2.8 之前的 chip 形态(无显式定义块)。",
            "v0.2.9+ 渲染器会输出 chip-body 块,重新渲染即可。",
        ))
    return issues


def _check_essay_talk(body: str, slug: str, title: str, url: str) -> List[Dict[str, str]]:
    issues: List[Dict[str, str]] = []
    s = (slug + " " + title + " " + url).lower()
    if not any(h in s for h in ESSAY_SLUG_HINTS):
        return issues
    # Essay-mode page should have 实践计划 / 结构说明 / 相关脉络
    missing = [m for m in ESSAY_REQUIRED_MARKERS if m not in body]
    if missing:
        issues.append(_mk_issue(
            "warning",
            "essay_missing_markers",
            f"essay / talk 页面缺少 essay-mode 标记: {', '.join(missing)}。可能是 v0.2.9 之前渲染的旧页面。",
            "重新用 v0.2.9+ renderer 渲染 essay 页面;Reproduction Plan 会切换为「实践计划」,Figures & Tables 会切换为「结构说明」,Related Work 会切换为「相关脉络」。",
        ))
    return issues


def _check_zh_cn_markers(body: str, slug: str, title: str) -> List[Dict[str, str]]:
    s = (slug + " " + title).lower()
    is_zh_page = (
        "-cn" in s
        or "cn-" in s
        or "human-inspired-memory-cn" in s
        or "second-me-human-inspired-memory" in s
        or re.search(r"[\u4e00-\u9fff]", title or "")
    )
    if not is_zh_page:
        return []
    present = [m for m in ZH_CN_MARKERS if m in body]
    if len(present) < 5:
        return [_mk_issue(
            "warning",
            "zh_cn_markers_weak",
            f"zh-CN 页面只检测到 {len(present)}/{len(ZH_CN_MARKERS)} 个中文 UI marker: {', '.join(present) or '(none)'}。",
            "重新用 v0.2.9+ renderer 渲染,确认 ui_language=zh-CN 且模板 zh-CN 文本未遗漏。",
        )]
    return []


# ----------------------------------------------------------------------------
# Manifest handling
# ----------------------------------------------------------------------------

def _load_manifest(args) -> Tuple[str, List[Dict[str, Any]]]:
    if args.manifest_url:
        status, body = _http_get(args.manifest_url, timeout=args.timeout)
        if status != 200 or not body:
            raise SystemExit(f"FAIL: cannot fetch manifest at {args.manifest_url} (HTTP {status})")
        try:
            data = json.loads(body)
        except json.JSONDecodeError as e:
            raise SystemExit(f"FAIL: manifest JSON parse error: {e}")
        return args.manifest_url, data.get("pages", [])
    if args.manifest_file:
        with open(args.manifest_file, "r", encoding="utf-8") as f:
            data = json.load(f)
        return f"file://{os.path.abspath(args.manifest_file)}", data.get("pages", [])
    raise SystemExit("FAIL: must supply --manifest-url or --manifest-file")


# ----------------------------------------------------------------------------
# Page audit
# ----------------------------------------------------------------------------

def _audit_page(url: str, title_hint: str, slug: str, args) -> Dict[str, Any]:
    page: Dict[str, Any] = {
        "url": url,
        "slug": slug,
        "title": title_hint,
        "http_status": 0,
        "fetched_bytes": 0,
        "issues": [],
    }
    status, body = _http_get(url, timeout=args.timeout)
    page["http_status"] = status
    page["fetched_bytes"] = len(body)
    if status != 200:
        page["issues"].append(_mk_issue(
            "error", "http_error",
            f"HTTP 状态非 200 (got {status})。",
            "检查 GitHub Pages 部署状态,确认页面在 gh-pages 分支存在。",
        ))
        page["status"] = "FAIL"
        return page
    if not body or len(body) < 200:
        page["issues"].append(_mk_issue(
            "error", "empty_body",
            f"页面内容为空或过短 ({len(body)} bytes)。",
            "检查生成器输出与发布流程。",
        ))
        page["status"] = "FAIL"
        return page

    actual_title = _extract_title(body)
    if actual_title:
        page["title"] = actual_title

    # Walk all checks
    issues: List[Dict[str, str]] = []
    issues.extend(_check_template_leak(body))
    issues.extend(_check_old_footer(body))
    issues.extend(_check_raw_dict(body))
    issues.extend(_check_resolver_trail(body, url))
    issues.extend(_check_claims(body))
    issues.extend(_check_glossary(body))
    issues.extend(_check_essay_talk(body, slug, page["title"], url))
    issues.extend(_check_zh_cn_markers(body, slug, page["title"]))

    page["issues"] = issues

    if any(i["severity"] == "error" for i in issues):
        page["status"] = "FAIL"
    elif any(i["severity"] == "warning" for i in issues):
        page["status"] = "WARN"
    else:
        page["status"] = "PASS"
    return page


# ----------------------------------------------------------------------------
# Reporting
# ----------------------------------------------------------------------------

def _overall_status(pages: List[Dict[str, Any]], manifest_ok: bool) -> str:
    if not manifest_ok:
        return "FAIL"
    if any(p.get("status") == "FAIL" for p in pages):
        return "FAIL"
    if any(p.get("status") == "WARN" for p in pages):
        return "WARN"
    return "PASS"


def _issue_counts(pages: List[Dict[str, Any]]) -> Dict[str, int]:
    out = {"error": 0, "warning": 0, "info": 0}
    for p in pages:
        for i in p.get("issues", []):
            sev = i.get("severity", "info")
            out[sev] = out.get(sev, 0) + 1
    return out


def _build_recommendations(pages: List[Dict[str, Any]]) -> List[str]:
    recs: List[str] = []
    codes_seen: Dict[str, int] = {}
    for p in pages:
        for i in p.get("issues", []):
            codes_seen[i["code"]] = codes_seen.get(i["code"], 0) + 1
    if codes_seen.get("template_leak"):
        recs.append(f"{codes_seen['template_leak']} 页面仍泄漏 template tag — 优先 batch re-render + republish。")
    if codes_seen.get("raw_dict"):
        recs.append(f"{codes_seen['raw_dict']} 页面仍输出 raw Python dict — 重新渲染使 normalize_five_cs 生效。")
    if codes_seen.get("old_footer"):
        recs.append(f"{codes_seen['old_footer']} 页面 footer 仍写 v0.1.0-alpha — 重新渲染以使用 generator_version。")
    if codes_seen.get("http_error"):
        recs.append(f"{codes_seen['http_error']} 页面 HTTP 非 200 — 检查 gh-pages 部署状态。")
    if codes_seen.get("missing_resolver_trail"):
        recs.append(f"{codes_seen['missing_resolver_trail']} 页面缺 Resolver Trail — v0.2.8 之前渲染,建议在 v0.2.11+ 分批重渲染。")
    if codes_seen.get("zh_cn_markers_weak"):
        recs.append(f"{codes_seen['zh_cn_markers_weak']} zh-CN 页面中文 marker 不足 — 重新渲染并确认 ui_language=zh-CN。")
    if codes_seen.get("essay_missing_markers"):
        recs.append(f"{codes_seen['essay_missing_markers']} essay 页面缺 essay-mode 标记 — 重新渲染以使用 is_essay_talk 切换。")
    if codes_seen.get("missing_glossary"):
        recs.append(f"{codes_seen['missing_glossary']} 页面缺 Glossary — 检查 paper_reading.json 的 glossary 字段。")
    if not recs:
        recs.append("所有页面通过审计;无需立即行动。")
    return recs


def _build_json_report(args, manifest_url: str, pages: List[Dict[str, Any]], manifest_ok: bool) -> Dict[str, Any]:
    counts = _issue_counts(pages)
    pass_n = sum(1 for p in pages if p.get("status") == "PASS")
    warn_n = sum(1 for p in pages if p.get("status") == "WARN")
    fail_n = sum(1 for p in pages if p.get("status") == "FAIL")
    return {
        "schema_version": "0.1.0",
        "generated_at": _dt.datetime.utcnow().isoformat() + "Z",
        "status": _overall_status(pages, manifest_ok),
        "site_root": args.site_root,
        "manifest_url": manifest_url,
        "manifest_ok": manifest_ok,
        "pages_total": len(pages),
        "pages_checked": len(pages),
        "pages_pass": pass_n,
        "pages_warn": warn_n,
        "pages_fail": fail_n,
        "issues_by_severity": counts,
        "pages": pages,
        "recommendations": _build_recommendations(pages),
    }


def _build_markdown_report(report: Dict[str, Any]) -> str:
    lines: List[str] = []
    lines.append(f"# Published Pages Regression Audit — {report['generated_at']}")
    lines.append("")
    lines.append(f"- **Status**: {report['status']}")
    lines.append(f"- **Site root**: {report['site_root']}")
    lines.append(f"- **Manifest URL**: {report['manifest_url']}")
    lines.append(f"- **Pages total / checked**: {report['pages_total']} / {report['pages_checked']}")
    lines.append(f"- **Pages PASS / WARN / FAIL**: {report['pages_pass']} / {report['pages_warn']} / {report['pages_fail']}")
    lines.append(f"- **Issues**: error={report['issues_by_severity']['error']} warning={report['issues_by_severity']['warning']} info={report['issues_by_severity']['info']}")
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append(
        "PASS: all pages HTTP 200 and no error-level issues. "
        "WARN: all pages accessible but legacy-render warnings present. "
        "FAIL: at least one page has template leak / raw dict / old footer / HTTP non-200."
    )
    lines.append("")

    lines.append("## Pages")
    lines.append("")
    lines.append("| # | URL | Status | HTTP | Title | Issues |")
    lines.append("|---|---|---|---|---|---|")
    for i, p in enumerate(report["pages"], 1):
        title = (p.get("title") or "")[:80].replace("|", "\\|")
        url = p.get("url", "")
        issues_short = ", ".join(sorted({i2["code"] for i2 in p.get("issues", [])})) or "—"
        lines.append(f"| {i} | {url} | {p.get('status', '?')} | {p.get('http_status', '?')} | {title} | {issues_short} |")
    lines.append("")

    lines.append("## Detailed issues")
    lines.append("")
    any_issue = False
    for p in report["pages"]:
        if not p.get("issues"):
            continue
        any_issue = True
        lines.append(f"### {p.get('url', '?')}")
        lines.append("")
        for i in p["issues"]:
            lines.append(f"- **[{i['severity']}]** `{i['code']}` — {i['message']}")
            if i.get("recommendation"):
                lines.append(f"  - 修复建议: {i['recommendation']}")
        lines.append("")
    if not any_issue:
        lines.append("_(no per-page issues)_")
        lines.append("")

    lines.append("## Recommendations")
    lines.append("")
    for r in report.get("recommendations", []):
        lines.append(f"- {r}")
    lines.append("")
    return "\n".join(lines)


# ----------------------------------------------------------------------------
# Self-test (used by validate.sh)
# ----------------------------------------------------------------------------

def _selftest(args) -> Dict[str, Any]:
    """Run synthetic pages through the same checks. Returns a report dict."""
    fake_manifest_pages = [
        {
            "slug": "fake-essay",
            "title": "Fake Essay — Self Test",
            "path": "/fake-essay/",
            "_url": "file://" + os.path.join(args.selftest_dir, "fake-essay.html"),
            "_expect": ["essay_missing_markers"],
        },
        {
            "slug": "fake-zhcn",
            "title": "Fake 中文",
            "path": "/fake-zhcn/",
            "_url": "file://" + os.path.join(args.selftest_dir, "fake-zhcn.html"),
            "_expect": ["zh_cn_markers_weak"],
        },
        {
            "slug": "fake-pass",
            "title": "Fake Pass",
            "path": "/fake-pass/",
            "_url": "file://" + os.path.join(args.selftest_dir, "fake-pass.html"),
            "_expect": [],
        },
        {
            "slug": "fake-template-leak",
            "title": "Fake Template Leak",
            "path": "/fake-template-leak/",
            "_url": "file://" + os.path.join(args.selftest_dir, "fake-template-leak.html"),
            "_expect": ["template_leak"],
        },
        {
            "slug": "fake-raw-dict",
            "title": "Fake Raw Dict",
            "path": "/fake-raw-dict/",
            "_url": "file://" + os.path.join(args.selftest_dir, "fake-raw-dict.html"),
            "_expect": ["raw_dict"],
        },
        {
            "slug": "fake-old-footer",
            "title": "Fake Old Footer",
            "path": "/fake-old-footer/",
            "_url": "file://" + os.path.join(args.selftest_dir, "fake-old-footer.html"),
            "_expect": ["old_footer"],
        },
    ]
    # monkey-patch _http_get for file:// urls
    import urllib.parse as _up

    def _file_get(url, timeout=20.0):
        parsed = _up.urlparse(url)
        path = _up.unquote(parsed.path)
        if not os.path.isfile(path):
            return 404, ""
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return 200, f.read()

    orig = globals()["_http_get"]
    globals()["_http_get"] = _file_get
    try:
        pages: List[Dict[str, Any]] = []
        for entry in fake_manifest_pages:
            url = entry["_url"]
            page = _audit_page(url, entry["title"], entry["slug"], args)
            pages.append(page)
    finally:
        globals()["_http_get"] = orig
    # Annotate pages with _expect + hit/miss for the validation script
    for entry, page in zip(fake_manifest_pages, pages):
        page["_expect"] = entry["_expect"]
        codes = {i["code"] for i in page.get("issues", [])}
        page["_expect_hit"] = sorted(c for c in entry["_expect"] if c in codes)
        page["_expect_miss"] = sorted(c for c in entry["_expect"] if c not in codes)
    return _build_json_report(args, "selftest://manifest", pages, manifest_ok=True)


# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------

def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Audit every page in a published_pages.json manifest against v0.2.9+ renderer expectations.",
    )
    parser.add_argument("--manifest-url", help="Live manifest URL (e.g. https://conanxin.github.io/paper-reading-pages/published_pages.json)")
    parser.add_argument("--manifest-file", help="Local manifest JSON path (alternative to --manifest-url)")
    parser.add_argument("--site-root", default="https://conanxin.github.io/paper-reading-pages", help="Site root used to build page URLs")
    parser.add_argument("--json-output", help="Write JSON report to this path")
    parser.add_argument("--markdown-output", help="Write Markdown report to this path")
    parser.add_argument("--warn-only", action="store_true", help="Always exit 0 unless something is structurally broken")
    parser.add_argument("--timeout", type=float, default=20.0, help="HTTP timeout per page (default 20s)")
    parser.add_argument("--max-pages", type=int, default=0, help="Cap pages to check (0 = no cap)")
    parser.add_argument("--include-root", action="store_true", help="Also audit the site root index.html")
    parser.add_argument("--strict", action="store_true", help="Treat warnings as failures for the overall status")
    parser.add_argument("--selftest-dir", help="(selftest) directory containing fake-*.html fixtures")
    args = parser.parse_args(argv)

    if args.selftest_dir:
        report = _selftest(args)
        if args.json_output:
            with open(args.json_output, "w", encoding="utf-8") as f:
                json.dump(report, f, ensure_ascii=False, indent=2)
        if args.markdown_output:
            with open(args.markdown_output, "w", encoding="utf-8") as f:
                f.write(_build_markdown_report(report))
        print(f"[selftest] overall={report['status']} pass={report['pages_pass']} warn={report['pages_warn']} fail={report['pages_fail']}")
        if args.strict and report["status"] != "PASS":
            return 2
        return 0

    # Normal run
    if not args.manifest_url and not args.manifest_file:
        parser.error("must supply --manifest-url or --manifest-file (or --selftest-dir for the smoke test)")

    try:
        manifest_url, manifest_pages = _load_manifest(args)
        manifest_ok = True
    except SystemExit as e:
        # Re-raise after writing partial report
        print(str(e), file=sys.stderr)
        if args.json_output:
            os.makedirs(os.path.dirname(os.path.abspath(args.json_output)) or ".", exist_ok=True)
            with open(args.json_output, "w", encoding="utf-8") as f:
                json.dump({
                    "status": "FAIL",
                    "site_root": args.site_root,
                    "manifest_url": args.manifest_url or "",
                    "manifest_ok": False,
                    "pages_total": 0,
                    "pages_checked": 0,
                    "pages_pass": 0,
                    "pages_warn": 0,
                    "pages_fail": 0,
                    "issues_by_severity": {"error": 1, "warning": 0, "info": 0},
                    "pages": [],
                    "recommendations": ["无法读取 manifest — 检查 --manifest-url 是否可访问。"],
                }, f, ensure_ascii=False, indent=2)
        return 1

    pages_to_check: List[Dict[str, Any]] = []
    for entry in manifest_pages:
        path = entry.get("path", "")
        url = urllib.parse.urljoin(args.site_root.rstrip("/") + "/", path.lstrip("/"))
        slug = entry.get("slug", path.strip("/").rstrip("/") or "index")
        title = entry.get("title", "")
        pages_to_check.append({"url": url, "title": title, "slug": slug})

    if args.include_root:
        pages_to_check.insert(0, {"url": args.site_root.rstrip("/") + "/", "title": "(site root)", "slug": "index"})

    if args.max_pages and args.max_pages > 0:
        pages_to_check = pages_to_check[: args.max_pages]

    audited: List[Dict[str, Any]] = []
    for entry in pages_to_check:
        try:
            p = _audit_page(entry["url"], entry["title"], entry["slug"], args)
        except Exception as e:
            p = {
                "url": entry["url"],
                "slug": entry["slug"],
                "title": entry["title"],
                "http_status": 0,
                "fetched_bytes": 0,
                "issues": [_mk_issue("error", "audit_crashed", f"审计脚本异常: {e}", "查看 audit_published_pages.py 错误日志。")],
                "status": "FAIL",
            }
        audited.append(p)

    report = _build_json_report(args, manifest_url, audited, manifest_ok)
    if args.strict and any(i["severity"] == "warning" for p in audited for i in p.get("issues", [])):
        report["status"] = "FAIL"

    if args.json_output:
        os.makedirs(os.path.dirname(os.path.abspath(args.json_output)) or ".", exist_ok=True)
        with open(args.json_output, "w", encoding="utf-8") as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
    if args.markdown_output:
        os.makedirs(os.path.dirname(os.path.abspath(args.markdown_output)) or ".", exist_ok=True)
        with open(args.markdown_output, "w", encoding="utf-8") as f:
            f.write(_build_markdown_report(report))

    print(f"[audit] overall={report['status']} pages={report['pages_total']} pass={report['pages_pass']} warn={report['pages_warn']} fail={report['pages_fail']}")

    if args.warn_only:
        return 0
    return 0 if report["status"] == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
